name: Android
on: [push]
jobs:
  build:
    name: NDK-R21e
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Android NDK R21e
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir build && cd build
        echo ${{ steps.setup-ndk.outputs.ndk-path }}
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=armeabi-v7a \
          # -DANDROID_NATIVE_API_LEVEL=21 \
          -DCMAKE_BUILD_TYPE=Release \
          ..
        cmake --build .
    - name: Upload GitHub Actions artifact of cmake-ndk build
      uses: actions/upload-artifact@v2
      with:
        name: asterism-android
        path: ${{ github.workspace }}/build/
