name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  Linux-mingw2windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: 'build'
      run: |
        apt-get install mingw-w64 -y
        mkdir build && cd build
        cmake \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
          -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
    - name: Upload GitHub Actions artifact of windows-x64
      uses: actions/upload-artifact@v2
      with:
        name: asterism-windows-x64
        path: ${{ github.workspace }}/build/
